import Head from 'next/head'
import {Card, Descriptions, Divider, List, Button} from 'antd';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Uber Eats Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Card title={'Order Title'}>

      </Card>
    </div>
  )
}
