import Head from 'next/head'
import '../styles/Home.module.css';
import DetailedOrder from "../components/DetailedOrder";
const Home = () => {

    // does it work?
  return (
    <div>
      <Head>
        <title>Uber Eats Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <DetailedOrder />
    </div>
  )
}


export default Home;
