import Head from 'next/head'
import '../styles/Home.module.css';
import Orders from "../components/Orders";
import {Layout, Image} from 'antd';

const Home = () => {
    // does it work?
  return (
    <div>
      <Head>
        <title>Uber Eats Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Orders />
    </div>
  )
}


export default Home;
